### ISSUE TITLE
Instagram token value is not accepted by Creepy

### ISSUE THREAD

**Issue by mintervino** [jkakavas/creepy#10] opened 2015-05-19 22:33 UTC
Hi,  I am able to configure Google, Flickr and Twitter but not Instagram.  I get the token value after pasting the link but after pasting it I receive "Please verify that the link you pasted was correct try running the wizard again".  I have attempted this numerous times.  I am on Win7, running Creepy 1.3

**Comment by jkakavas** [comment] 2015-05-20 10:10
I just completed the process of configuring Instagram plugin in 2 different win7 VM, with the version downloaded from www.geocreepy.com so I can verify that it is generally working. Can you please send me the log files that you will find in the .creepy folder in your user's home folder ( C:\Users\YOURUSERAME ) so that I can take a look and help you figure out what the problem is ?

**Comment by mintervino** [comment] 2015-05-20 16:16
I intended on deleting the contents of the log file at .creepy/creepy_main, replicating the issue then submitting the log file for your review.  But now Creepy has accepted the token value - and I cannot create the issue again.  Thank you for your prompt attention and your work.

**Comment by jkakavas** [comment] 2015-05-21 06:50
Great, good to hear !  I ll close this for now, but feel free to reopen it if you come across the same issue again.

**Closed by jkakavas** 2015-05-21 06:50 UTC

**Comment by red-green** [comment] 2015-12-05 00:57
I have the same issue on Mac OS. I haven't tried any other plugins.

**Comment by red-green** [comment] 2015-12-05 01:01
It seems that the .app needs to be in the /Applications folder, not from another folder where I was running it from.
